name: "Build Container images"

on:
  push:
    branches:
      - main

jobs:
  build-base:
    name: Build base images
    runs-on:
      - ubuntu-24.04
    strategy:
      matrix:
        container: [core, db, exporter, jobservice, log, nginx, portal, prepare, redis, registryctl, registry, trivy-adapter]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.2
      - uses: docker/login-action@v3
        with:
          registry: harbor.nirvati.org
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check out copy to subdirectory for go
        uses: actions/checkout@v4
        with:
          path: src/github.com/goharbor/harbor

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: make/photon/${{ matrix.container }}
          file: make/photon/${{ matrix.container }}/Dockerfile.base
          push: true
          tags: harbor.nirvati.org/registry/${{ matrix.container }}-base:latest
